require "nvchad.mappings"

local map = vim.keymap.set

map("n", "<C-x>@sg", function() require("neogit").open({kind = "auto"}) end, { desc = "Open Neogit", silent = true})
map("n", "<leader>ff", function()
   require'telescope.builtin'.find_files({find_command = {'rg', '--files', '--hidden', '-g', '!.git', '-g', '!.github', '-g', '!node_modules' }, cwd = vim.fn.expand('%:p:h')})
end, { desc = "Find files", nowait = true, silent = true })
map("n", "<D-f>", function()
   require'telescope.builtin'.find_files({find_command = {'rg', '--files', '--hidden', '-g', '!.git', '-g', '!.github', '-g', '!node_modules' }, cwd = vim.fn.expand('%:p:h')})
end, { desc = "Find files", nowait = true, silent = true })
map("n", "<C-x>@sf", function()
   require'telescope.builtin'.find_files({find_command = {'rg', '--files', '--hidden', '-g', '!.git', '-g', '!.github', '-g', '!node_modules' }, cwd = vim.fn.expand('%:p:h')})
end, { desc = "Find files", nowait = true, silent = true })
map("n", "<C-x><C-f>", function()
   require'telescope.builtin'.find_files({find_command = {'rg', '--files', '--hidden', '-g', '!.git', '-g', '!.github', '-g', '!node_modules' }, cwd = vim.fn.expand('%:p:h')})
end, { desc = "Find files", nowait = true, silent = true })
map("n", "<leader>fa", function()
   require'telescope.builtin'.find_files({find_command = {'rg', '--files', '--hidden', '-g', '!.git', '-g', '!.github', '-g', '!node_modules' }})
end, { desc = "Find all", nowait = true, silent = true })
map("n", "<leader>pf", function()
   require'telescope.builtin'.find_files({find_command = {'rg', '--files', '--hidden', '-g', '!.git', '-g', '!.github', '-g', '!node_modules' }})
end, { desc = "Find all", nowait = true, silent = true })
map("n", "<D-o>", function()
   require'telescope.builtin'.find_files({find_command = {'rg', '--files', '--hidden', '-g', '!.git', '-g', '!.github', '-g', '!node_modules' }})
end, { desc = "Find all", nowait = true, silent = true })
map("n", "<C-x>@so", function()
   require'telescope.builtin'.find_files({find_command = {'rg', '--files', '--hidden', '-g', '!.git', '-g', '!.github', '-g', '!node_modules' }})
end, { desc = "Find all", nowait = true, silent = true })
map("n", "<leader>gl", "<cmd> Telescope git_commits <CR>", { desc = "Git commits" , nowait = true, silent = true })
map("n", "<leader>gc", "<cmd> Telescope git_branches <CR>", { desc = "Git branches" , nowait = true, silent = true })
map("n", "<leader>gs", function() require("neogit").open({kind = "auto"}) end, { desc = "Git status" , nowait = true, silent = true })
map("n", "<D-g>", function() require("neogit").open({kind = "auto"}) end, { desc = "Git status" , nowait = true, silent = true })
map({"n", "x", "o"}, "]h", function()
  local gs = require("gitsigns")
  gs.next_hunk()
end, { desc = "Next Hunk" })


map({"n", "x", "o"}, "[h", function()
  local gs = require("gitsigns")
  gs.prev_hunk()
end, { desc = "Prev Hunk" })
